[
  {
      "id": 1,
      "rental_name": "Fantastic Mobile Home By The River",
      "rental_description": "Fantastic Mobile Home By The River is fun for the whole family",
      "rating": 31.1,
      "guestMax": 9,
      "pricePerNight": 421,
      "discountPricePerNight": 336.8,
      "weeklyDiscount": 0,
      "cleaningFee": 116,
      "serviceFee": 29,
      "numOfReviews": 398
  },
  {
      "id": 2,
      "rental_name": "Beautiful House By The Sea",
      "rental_description": "Beautiful House By The Sea is best known for its ghost sightings",
      "rating": 30.9,
      "guestMax": 5,
      "pricePerNight": 231,
      "discountPricePerNight": 184.8,
      "weeklyDiscount": 1,
      "cleaningFee": 163,
      "serviceFee": 75,
      "numOfReviews": 162
  },
  {
      "id": 3,
      "rental_name": "Wonderful Apartment Close To Downtown",
      "rental_description": "Wonderful Apartment Close To Downtown is best known for its ghost sightings",
      "rating": 31.2,
      "guestMax": 9,
      "pricePerNight": 318,
      "discountPricePerNight": 254.4,
      "weeklyDiscount": 0,
      "cleaningFee": 108,
      "serviceFee": 49,
      "numOfReviews": 223
  },
  {
      "id": 4,
      "rental_name": "Wonderful Castle By The Sea",
      "rental_description": "Wonderful Castle By The Sea is fun for the whole family",
      "rating": 30.2,
      "guestMax": 5,
      "pricePerNight": 201,
      "discountPricePerNight": 160.8,
      "weeklyDiscount": 1,
      "cleaningFee": 89,
      "serviceFee": 23,
      "numOfReviews": 41
  },
  {
      "id": 5,
      "rental_name": "Peaceful Space Ship Close To Downtown",
      "rental_description": "Peaceful Space Ship Close To Downtown is fun for the whole family",
      "rating": 30.1,
      "guestMax": 7,
      "pricePerNight": 349,
      "discountPricePerNight": 279.2,
      "weeklyDiscount": 0,
      "cleaningFee": 86,
      "serviceFee": 48,
      "numOfReviews": 504
  },
  {
      "id": 6,
      "rental_name": "Peaceful Apartment Close To Downtown",
      "rental_description": "Peaceful Apartment Close To Downtown will make you never want to leave",
      "rating": 30.7,
      "guestMax": 2,
      "pricePerNight": 98,
      "discountPricePerNight": 78.4,
      "weeklyDiscount": 0,
      "cleaningFee": 79,
      "serviceFee": 79,
      "numOfReviews": 639
  },
  {
      "id": 7,
      "rental_name": "Unforgettable Tree House In The Countryside",
      "rental_description": "Unforgettable Tree House In The Countryside is fun for the whole family",
      "rating": 31.2,
      "guestMax": 3,
      "pricePerNight": 450,
      "discountPricePerNight": 360,
      "weeklyDiscount": 1,
      "cleaningFee": 64,
      "serviceFee": 27,
      "numOfReviews": 544
  },
  {
      "id": 8,
      "rental_name": "Happening Bio Dome By The Sea",
      "rental_description": "Happening Bio Dome By The Sea will make you never want to leave",
      "rating": 30.2,
      "guestMax": 7,
      "pricePerNight": 391,
      "discountPricePerNight": 312.8,
      "weeklyDiscount": 1,
      "cleaningFee": 36,
      "serviceFee": 57,
      "numOfReviews": 49
  },
  {
      "id": 9,
      "rental_name": "Amazing Castle Close To Downtown",
      "rental_description": "Amazing Castle Close To Downtown is also occupied by 7 cats",
      "rating": 31,
      "guestMax": 8,
      "pricePerNight": 151,
      "discountPricePerNight": 120.8,
      "weeklyDiscount": 0,
      "cleaningFee": 30,
      "serviceFee": 40,
      "numOfReviews": 328
  },
  {
      "id": 10,
      "rental_name": "Glorious Bio Dome Close To Downtown",
      "rental_description": "Glorious Bio Dome Close To Downtown is the best place to stay EVER",
      "rating": 30.4,
      "guestMax": 2,
      "pricePerNight": 274,
      "discountPricePerNight": 219.2,
      "weeklyDiscount": 0,
      "cleaningFee": 59,
      "serviceFee": 78,
      "numOfReviews": 342
  }
]